#aws-nuke-service.yaml
template_path: aws-nuke-service.yaml 

parameters:
  GitUser: adamcousins
  GitRepo: aws-nuke-service
  GitBranch: master
  GitToken: !ssm /github/token
  AWSNukeConfigFile: aws-nuke-config/config.yaml
  AWSNukeProfileName: nuke
  AWSNukeDryRun: "true" #Set to false to terminate resources
  NotificationEmailAddress: example@example.com
  WhenToExecute: cron(0 14 * * ? *)
  RetentionInDays: "30"